### ISSUE TITLE
Improve GitHub publishing for logged in users

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1473]
While trying to publish a gist to my user account, the following happens:

* Click File -> Publish -> User Gist
* Wait (sometimes a while) for the dialog to come up
* Dialog appears on a different monitor from where I'm running nteract
* Publish ends up erroring
* I start a separate notebook, try publishing, notice this error

![screen shot 2017-02-16 at 9 25 03 am](https://cloud.githubusercontent.com/assets/836375/23032625/e9a8579c-f429-11e6-99a6-605aace24e05.png)

It looks like globals are attempted to be used across the app? This does not look like the state is being synchronized well.

**Comment by jdetle** [comment]
Oh no! I'll try to reproduce and figure out how to fix this issue.

**Comment by rgbkrk** [comment]
Here's what I'm getting right now after logging in to publish:

![screen shot 2017-03-02 at 4 21 16 pm](https://cloud.githubusercontent.com/assets/836375/23533098/645cd630-ff64-11e6-85b3-c7e700526e78.png)

nteract 0.1.0

**Comment by jdetle** [comment]
I'll tackle this. Sorry about the issue!

**Comment by AlJohri** [comment]
hi guys,

i'm getting the same issue. the console shows specifically this error:

```
https://github.com/login/oauth/authorize?client_id=undefined&scope=gist&redirect_uri=https://oauth.nteract.io/callback&state=d4c921345af38373 Failed to load resource: the server responded with a status of 404 (Not Found)
```

guessing there's some error in here: https://github.com/nteract/oauth-server/blob/master/index.js

**Comment by AlJohri** [comment]
since we're on the issue of github user gists, it would be pretty helpful if the gists could either have an option to publish as secret or publish as secret by default (where users can choose to make it public when they're done). it's hard to use for work if its public by default

**Comment by jdetle** [comment]
Its secret by default? Or at least I thought... Will look into this right now.

**Comment by AlJohri** [comment]
That could be the case! I just assumed it wasn't, haven't been able to try it yet. In which case, the wording should probably be adjusted to say private or secret gist.

**Comment by jdetle** [comment]
Right, the problem here is that the current setup is that if the gist you're publishing has been made public, it won't set it back to secret. This is a legitimate concern though and I'll have to do some thinking on how to make this more straight forward, thanks.

**Comment by rgbkrk** [comment]
Note: our github publishing app now stays online with at least one node at all times now.

**Comment by rgbkrk** [comment]
@jdetle I'm going to go ahead and un-assign you from this issue since no one has touched it, so that it remains open for someone else to tackle.

**Comment by jdetle** [comment]
Thanks.

**Comment by dar10p** [comment]
![Screen Shot 2019-07-19 at 14 15 19](https://user-images.githubusercontent.com/49408138/61556382-a5998f80-aa2f-11e9-9718-3324049dae1a.jpg)

It seems 'publish to Gist' is broken again =(

**Comment by captainsafia** [comment]
@dar10p Thanks for opening this issue!

It looks like our oauth server deployment for Gist publishing is misconfigured on our deployment service. I'll go ahead and fix this later today.

**Comment by captainsafia** [comment]
This is fixed now.

**Comment by dar10p** [comment]
I still get the same 404 error... don't know if there is something I need to do.

**Comment by captainsafia** [comment]
@dar10p Try now?

**Comment by dar10p** [comment]
Working now. Thx!
