### ISSUE TITLE
nteract will start python 2 instead of python3

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#1701]
This shows a python 3 notebook.
![bildschirmfoto 2017-05-19 um 12 30 24](https://cloud.githubusercontent.com/assets/13285808/26244162/f42dcfaa-3c8e-11e7-95b7-564c743901e4.png)

The output of `kernelspecs` differs from `jupyter kernelspec`.  `jupyter kernelspec` uses the complete path to the executable whereas `kernelspecs` has the same `argv` for python 2 and python3.

**Comment by rgbkrk** [comment]
Hmmm, I take it our merge of the assumed python and the reported kernelspecs isn't happening properly.

**Comment by karkraeg** [comment]
Same problem here. Using the Juypter Notebook the ipython kernels are recognised correctly.
![06-05-2017-19 00 52](https://cloud.githubusercontent.com/assets/8436596/26794288/6068dd32-4a21-11e7-9eaf-62c8d1a29188.jpg)
----
edit: turns out the `argv` in `/usr/local/share/jupyter/kernels/python3/kernel.json` was set to `python` not `python3`. Seems to be working now.

**Comment by lgeiger** [comment]
I can't reproduce this issue anymore on master. I think it was fixed with the latest `kernelspecs` update.

**Comment by rgbkrk** [comment]
Yeah that's correct. Higher precedence kernels no longer overwrite each other.

**Comment by guaguanco** [comment]
The problem is still there, caused by `pip3 install ipykernel` which creates a wrong `/usr/local/share/jupyter/kernels/python3/kernel.json` file with `python` in place of `python3`.

This breaks nteract 0.0.5 which cannot start the default kernel unless ipykernel for py2 is installed as well. I opened an issue on ipython repository
